<?php

namespace App\Test\TestDoubles;

use App\Utilities\ProcessSet;

class ProcessSetDouble extends ProcessSet
{
    public function initIteratorSeed($followers, $path='0') : array
    {
        return parent::initIteratorSeed($followers, $path); // TODO: Change the autogenerated stub
    }

    public function setKeyedByPrereq(array $array)
    {
        $this->keyedByPrereq = $array;
    }

}
