<?php

namespace App\Test\TestDoubles;

use App\Utilities\ProcessSet;

class ProcessSetDouble extends ProcessSet
{
    public function childIteratorSeed($followers)
    {
        return parent::childIteratorSeed($followers); // TODO: Change the autogenerated stub
    }

    public function setKeyedByPrereq(array $array)
    {
        $this->keyedByPrereq = $array;
    }

}
