<?php

namespace App\Test\TestDoubles;

use App\Utilities\ProcessSet;

class ProcessSetDouble extends ProcessSet
{

    public function getDefaultPropertyValues() {
        return get_class_vars(get_class($this));
    }

    public function getCurrentPropertyValues() {
        return get_object_vars($this);
    }

    public function initIteratorSeed($followers = null, $path='0') : array
    {
        return parent::initIteratorSeed($followers, $path);
    }

    public function setKeyedByPrereq(array $array)
    {
        $this->keyedByPrereq = $array;
    }

    public function getIteratorSeed()
    {
        return $this->iteratorSeed;
    }

    public function getPrereqChain()
    {
        return $this->prereqChain;
    }

    public function setThreadPaths()
    {
        return parent::setThreadPaths(); // TODO: Change the autogenerated stub
    }


}
